/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RastrearRouteImport } from './routes/rastrear'
import { Route as MeusPedidosRouteImport } from './routes/meus-pedidos'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProdutoIdRouteImport } from './routes/produto.$id'
import { Route as MeusPedidosIdRouteImport } from './routes/meus-pedidos.$id'
import { Route as ComprovanteIdRouteImport } from './routes/comprovante.$id'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as CheckoutSucessoIdRouteImport } from './routes/checkout.sucesso.$id'
import { Route as ApiPublicMpWebhookRouteImport } from './routes/api/public/mp-webhook'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as AuthenticatedAdminSalesRouteImport } from './routes/_authenticated/admin.sales'
import { Route as AuthenticatedAdminProductsRouteImport } from './routes/_authenticated/admin.products'
import { Route as AuthenticatedAdminPdvRouteImport } from './routes/_authenticated/admin.pdv'
import { Route as AuthenticatedAdminOrdersRouteImport } from './routes/_authenticated/admin.orders'
import { Route as AuthenticatedAdminFinanceRouteImport } from './routes/_authenticated/admin.finance'
import { Route as AuthenticatedAdminContentRouteImport } from './routes/_authenticated/admin.content'
import { Route as AuthenticatedAdminCategoriesRouteImport } from './routes/_authenticated/admin.categories'
import { Route as AuthenticatedAdminBackupRouteImport } from './routes/_authenticated/admin.backup'
import { Route as AuthenticatedAdminAboutRouteImport } from './routes/_authenticated/admin.about'

const RastrearRoute = RastrearRouteImport.update({
  id: '/rastrear',
  path: '/rastrear',
  getParentRoute: () => rootRouteImport,
} as any)
const MeusPedidosRoute = MeusPedidosRouteImport.update({
  id: '/meus-pedidos',
  path: '/meus-pedidos',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutoIdRoute = ProdutoIdRouteImport.update({
  id: '/produto/$id',
  path: '/produto/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MeusPedidosIdRoute = MeusPedidosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => MeusPedidosRoute,
} as any)
const ComprovanteIdRoute = ComprovanteIdRouteImport.update({
  id: '/comprovante/$id',
  path: '/comprovante/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const CheckoutSucessoIdRoute = CheckoutSucessoIdRouteImport.update({
  id: '/sucesso/$id',
  path: '/sucesso/$id',
  getParentRoute: () => CheckoutRoute,
} as any)
const ApiPublicMpWebhookRoute = ApiPublicMpWebhookRouteImport.update({
  id: '/api/public/mp-webhook',
  path: '/api/public/mp-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSalesRoute = AuthenticatedAdminSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminProductsRoute =
  AuthenticatedAdminProductsRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPdvRoute = AuthenticatedAdminPdvRouteImport.update({
  id: '/pdv',
  path: '/pdv',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminOrdersRoute =
  AuthenticatedAdminOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminFinanceRoute =
  AuthenticatedAdminFinanceRouteImport.update({
    id: '/finance',
    path: '/finance',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminContentRoute =
  AuthenticatedAdminContentRouteImport.update({
    id: '/content',
    path: '/content',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCategoriesRoute =
  AuthenticatedAdminCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBackupRoute =
  AuthenticatedAdminBackupRouteImport.update({
    id: '/backup',
    path: '/backup',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAboutRoute = AuthenticatedAdminAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/meus-pedidos': typeof MeusPedidosRouteWithChildren
  '/rastrear': typeof RastrearRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/comprovante/$id': typeof ComprovanteIdRoute
  '/meus-pedidos/$id': typeof MeusPedidosIdRoute
  '/produto/$id': typeof ProdutoIdRoute
  '/admin/about': typeof AuthenticatedAdminAboutRoute
  '/admin/backup': typeof AuthenticatedAdminBackupRoute
  '/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/admin/content': typeof AuthenticatedAdminContentRoute
  '/admin/finance': typeof AuthenticatedAdminFinanceRoute
  '/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/admin/pdv': typeof AuthenticatedAdminPdvRoute
  '/admin/products': typeof AuthenticatedAdminProductsRoute
  '/admin/sales': typeof AuthenticatedAdminSalesRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/api/public/mp-webhook': typeof ApiPublicMpWebhookRoute
  '/checkout/sucesso/$id': typeof CheckoutSucessoIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/meus-pedidos': typeof MeusPedidosRouteWithChildren
  '/rastrear': typeof RastrearRoute
  '/comprovante/$id': typeof ComprovanteIdRoute
  '/meus-pedidos/$id': typeof MeusPedidosIdRoute
  '/produto/$id': typeof ProdutoIdRoute
  '/admin/about': typeof AuthenticatedAdminAboutRoute
  '/admin/backup': typeof AuthenticatedAdminBackupRoute
  '/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/admin/content': typeof AuthenticatedAdminContentRoute
  '/admin/finance': typeof AuthenticatedAdminFinanceRoute
  '/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/admin/pdv': typeof AuthenticatedAdminPdvRoute
  '/admin/products': typeof AuthenticatedAdminProductsRoute
  '/admin/sales': typeof AuthenticatedAdminSalesRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/api/public/mp-webhook': typeof ApiPublicMpWebhookRoute
  '/checkout/sucesso/$id': typeof CheckoutSucessoIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/meus-pedidos': typeof MeusPedidosRouteWithChildren
  '/rastrear': typeof RastrearRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/comprovante/$id': typeof ComprovanteIdRoute
  '/meus-pedidos/$id': typeof MeusPedidosIdRoute
  '/produto/$id': typeof ProdutoIdRoute
  '/_authenticated/admin/about': typeof AuthenticatedAdminAboutRoute
  '/_authenticated/admin/backup': typeof AuthenticatedAdminBackupRoute
  '/_authenticated/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/_authenticated/admin/content': typeof AuthenticatedAdminContentRoute
  '/_authenticated/admin/finance': typeof AuthenticatedAdminFinanceRoute
  '/_authenticated/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/_authenticated/admin/pdv': typeof AuthenticatedAdminPdvRoute
  '/_authenticated/admin/products': typeof AuthenticatedAdminProductsRoute
  '/_authenticated/admin/sales': typeof AuthenticatedAdminSalesRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/api/public/mp-webhook': typeof ApiPublicMpWebhookRoute
  '/checkout/sucesso/$id': typeof CheckoutSucessoIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/checkout'
    | '/meus-pedidos'
    | '/rastrear'
    | '/admin'
    | '/comprovante/$id'
    | '/meus-pedidos/$id'
    | '/produto/$id'
    | '/admin/about'
    | '/admin/backup'
    | '/admin/categories'
    | '/admin/content'
    | '/admin/finance'
    | '/admin/orders'
    | '/admin/pdv'
    | '/admin/products'
    | '/admin/sales'
    | '/admin/settings'
    | '/admin/users'
    | '/api/public/mp-webhook'
    | '/checkout/sucesso/$id'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/checkout'
    | '/meus-pedidos'
    | '/rastrear'
    | '/comprovante/$id'
    | '/meus-pedidos/$id'
    | '/produto/$id'
    | '/admin/about'
    | '/admin/backup'
    | '/admin/categories'
    | '/admin/content'
    | '/admin/finance'
    | '/admin/orders'
    | '/admin/pdv'
    | '/admin/products'
    | '/admin/sales'
    | '/admin/settings'
    | '/admin/users'
    | '/api/public/mp-webhook'
    | '/checkout/sucesso/$id'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/checkout'
    | '/meus-pedidos'
    | '/rastrear'
    | '/_authenticated/admin'
    | '/comprovante/$id'
    | '/meus-pedidos/$id'
    | '/produto/$id'
    | '/_authenticated/admin/about'
    | '/_authenticated/admin/backup'
    | '/_authenticated/admin/categories'
    | '/_authenticated/admin/content'
    | '/_authenticated/admin/finance'
    | '/_authenticated/admin/orders'
    | '/_authenticated/admin/pdv'
    | '/_authenticated/admin/products'
    | '/_authenticated/admin/sales'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/users'
    | '/api/public/mp-webhook'
    | '/checkout/sucesso/$id'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CheckoutRoute: typeof CheckoutRouteWithChildren
  MeusPedidosRoute: typeof MeusPedidosRouteWithChildren
  RastrearRoute: typeof RastrearRoute
  ComprovanteIdRoute: typeof ComprovanteIdRoute
  ProdutoIdRoute: typeof ProdutoIdRoute
  ApiPublicMpWebhookRoute: typeof ApiPublicMpWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rastrear': {
      id: '/rastrear'
      path: '/rastrear'
      fullPath: '/rastrear'
      preLoaderRoute: typeof RastrearRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meus-pedidos': {
      id: '/meus-pedidos'
      path: '/meus-pedidos'
      fullPath: '/meus-pedidos'
      preLoaderRoute: typeof MeusPedidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produto/$id': {
      id: '/produto/$id'
      path: '/produto/$id'
      fullPath: '/produto/$id'
      preLoaderRoute: typeof ProdutoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meus-pedidos/$id': {
      id: '/meus-pedidos/$id'
      path: '/$id'
      fullPath: '/meus-pedidos/$id'
      preLoaderRoute: typeof MeusPedidosIdRouteImport
      parentRoute: typeof MeusPedidosRoute
    }
    '/comprovante/$id': {
      id: '/comprovante/$id'
      path: '/comprovante/$id'
      fullPath: '/comprovante/$id'
      preLoaderRoute: typeof ComprovanteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/checkout/sucesso/$id': {
      id: '/checkout/sucesso/$id'
      path: '/sucesso/$id'
      fullPath: '/checkout/sucesso/$id'
      preLoaderRoute: typeof CheckoutSucessoIdRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/api/public/mp-webhook': {
      id: '/api/public/mp-webhook'
      path: '/api/public/mp-webhook'
      fullPath: '/api/public/mp-webhook'
      preLoaderRoute: typeof ApiPublicMpWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/sales': {
      id: '/_authenticated/admin/sales'
      path: '/sales'
      fullPath: '/admin/sales'
      preLoaderRoute: typeof AuthenticatedAdminSalesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/products': {
      id: '/_authenticated/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AuthenticatedAdminProductsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/pdv': {
      id: '/_authenticated/admin/pdv'
      path: '/pdv'
      fullPath: '/admin/pdv'
      preLoaderRoute: typeof AuthenticatedAdminPdvRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/orders': {
      id: '/_authenticated/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AuthenticatedAdminOrdersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/finance': {
      id: '/_authenticated/admin/finance'
      path: '/finance'
      fullPath: '/admin/finance'
      preLoaderRoute: typeof AuthenticatedAdminFinanceRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/content': {
      id: '/_authenticated/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AuthenticatedAdminContentRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/categories': {
      id: '/_authenticated/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AuthenticatedAdminCategoriesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/backup': {
      id: '/_authenticated/admin/backup'
      path: '/backup'
      fullPath: '/admin/backup'
      preLoaderRoute: typeof AuthenticatedAdminBackupRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/about': {
      id: '/_authenticated/admin/about'
      path: '/about'
      fullPath: '/admin/about'
      preLoaderRoute: typeof AuthenticatedAdminAboutRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAboutRoute: typeof AuthenticatedAdminAboutRoute
  AuthenticatedAdminBackupRoute: typeof AuthenticatedAdminBackupRoute
  AuthenticatedAdminCategoriesRoute: typeof AuthenticatedAdminCategoriesRoute
  AuthenticatedAdminContentRoute: typeof AuthenticatedAdminContentRoute
  AuthenticatedAdminFinanceRoute: typeof AuthenticatedAdminFinanceRoute
  AuthenticatedAdminOrdersRoute: typeof AuthenticatedAdminOrdersRoute
  AuthenticatedAdminPdvRoute: typeof AuthenticatedAdminPdvRoute
  AuthenticatedAdminProductsRoute: typeof AuthenticatedAdminProductsRoute
  AuthenticatedAdminSalesRoute: typeof AuthenticatedAdminSalesRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAboutRoute: AuthenticatedAdminAboutRoute,
  AuthenticatedAdminBackupRoute: AuthenticatedAdminBackupRoute,
  AuthenticatedAdminCategoriesRoute: AuthenticatedAdminCategoriesRoute,
  AuthenticatedAdminContentRoute: AuthenticatedAdminContentRoute,
  AuthenticatedAdminFinanceRoute: AuthenticatedAdminFinanceRoute,
  AuthenticatedAdminOrdersRoute: AuthenticatedAdminOrdersRoute,
  AuthenticatedAdminPdvRoute: AuthenticatedAdminPdvRoute,
  AuthenticatedAdminProductsRoute: AuthenticatedAdminProductsRoute,
  AuthenticatedAdminSalesRoute: AuthenticatedAdminSalesRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface CheckoutRouteChildren {
  CheckoutSucessoIdRoute: typeof CheckoutSucessoIdRoute
}

const CheckoutRouteChildren: CheckoutRouteChildren = {
  CheckoutSucessoIdRoute: CheckoutSucessoIdRoute,
}

const CheckoutRouteWithChildren = CheckoutRoute._addFileChildren(
  CheckoutRouteChildren,
)

interface MeusPedidosRouteChildren {
  MeusPedidosIdRoute: typeof MeusPedidosIdRoute
}

const MeusPedidosRouteChildren: MeusPedidosRouteChildren = {
  MeusPedidosIdRoute: MeusPedidosIdRoute,
}

const MeusPedidosRouteWithChildren = MeusPedidosRoute._addFileChildren(
  MeusPedidosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CheckoutRoute: CheckoutRouteWithChildren,
  MeusPedidosRoute: MeusPedidosRouteWithChildren,
  RastrearRoute: RastrearRoute,
  ComprovanteIdRoute: ComprovanteIdRoute,
  ProdutoIdRoute: ProdutoIdRoute,
  ApiPublicMpWebhookRoute: ApiPublicMpWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
